pipeline {
    agent {
        docker {
            image 'qnib/pytest' 
        }
    }
    stages{
        stage('Test') {
            steps{
                sh '''
                coverage run --source tests/ -m pytest tests/ -s -vv --junit-xml=src/tests/unit_integration_test_results.xml
                coverage html --fail-under=86
                '''
            }
        }
    }
    post {
    always {
      // for coverage reports generated by pytest
      publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: false, reportDir: 'htmlcov', reportFiles: 'index.html', reportName: 'Coverage Report', reportTitles: ''])
    }
  }
}
